# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: maquiadev1
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-socket
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-socket

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - {"Fn::GetAtt": ["ConnectionsTable", "Arn"]}
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - arn:aws:execute-api:*:*:*/@connections/*

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  connect:
    handler: src/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  message:
    handler: src/message.handler
    events:
      - websocket:
          route: sendMessage
plugins:
  - serverless-offline

